# .streamlit/secrets.toml


db_username = "Bhanu"
db_password = "Tharakram123"

[data]
file_path = "C:/Users/Bhanu prakash/OneDrive - Vijaybhoomi International School/Desktop/11_07_24_Streamlit/Corp_W_SF_data.csv"